### ISSUE TITLE
Create a temp `setVariable` function, where `value` must be `string`

### ISSUE THREAD

**Issue by Levysantiago** [GifflarJS-Framework/gifflar-library#94]
- In `contentModel`, copy the `setVariable` function and paste as another function of `contentModel`, so you rename it to `setVariable2`.  
- Then you rename the `value` parameter to `expression`, which also must be type `string`, same as `setAssignment`. 
- Create a expressionModel inside the `setVariable2` function
- Create the `newVariable` passing the expression `value` to the variable `value`.

**Comment by SincerelyBrittany** [comment]
Hi, I am interested in working on this issue. The goal is to update the setVariable value in the [contentModel.ts](https://github.com/GifflarJS-Framework/gifflar-library/blob/main/src/modules/models/definitions/content/implementations/ContentModel.ts#L143) to IExpression instead of INewContract, right?

**Comment by Levysantiago** [comment]
Hello @SincerelyBrittany ! It is really nice to have you here. Firstly, I`m sorry the repo doesn`t have yet a good documentation or contributions orientations. Since it was only me working in this project yet haha. But I will explain more about how you can proceed in solving this issue.

Its not only updating contentModel. We must change the `value` type in `IVariable` first, because this is the definition of a variable in solidity ([Solidity Grammar](https://docs.soliditylang.org/en/develop/grammar.html) I`m following this grammar here). But here is one thing, I realized that `IVariable` is attached to many other components and automatic tests, so maybe the issue is not so simple. But I can make it simple, so you can get started. I`m going to rename the issue and explain what you can do.

For now, you could do the following: In `contentModel`, you copy the `setVariable` function and paste as another function of `contentModel`, so you rename it to `setVariable2`.  

Then you rename the `value` parameter to `expression`, which also must be type `string`, same as `setAssignment`. So you create a expressionModel inside the `setVariable2` function and create the `newVariable` passing the expression `value` to the variable `value`.

This would be good to start updating the variable `value` type to IExpression. Later, the `setValue2` will be the new `setValue`. But I`ll attach this to another issue and explain in more details.

Let me know if you would like to continue contributing with this issue, then I can send you some contributions recommendations 😃 .

**Comment by SincerelyBrittany** [comment]
Thank you so much for explaining that @Levysantiago. Yes, I would like to continue contributing to this issue and would love it if you can send more contributions recommendations. 🙂

**Comment by Levysantiago** [comment]
Great! Well here we go:

- First you make a fork of the repo. So you can use your fork to update the project.
- Every updates you can make in `dev` branch, and later I can merge to the `main` branch when there is a stable version in `dev` branch with significant updates made.
- Once you finish the updates, you can make a Pull Request to the main repo, so I`ll revise the updates you made, If there is any modification to be made I`ll set a recommendation in the pull request. If is all good, I will merge your `dev` updates to the main repository `dev` branch.
- I recommend before pushing updates and opening a pull request, you run the automatic tests with `npm test` or `yarn test`. If all passed, then you can push, and open the pull request. All the tests will run again by the Github Actions.

*About the commits pattern:*
- When making a commit, if its a commit that is just related to an issue, you first define what is the issue this commit is related to, using brackets like this: `"[#<issue_number>]..."`, than you define what is the type of the commit (`feat`, `refactor`...) like this `"[#<issue_number>] <commit_type>: ..."`. Then you set the commit message. The final commit definition is this: `"[#<issue_number>] <commit_type>: <commit_message>"`. Example: e1ae3da779c357078908e6372f6fdcf606f59582
- If the commit is closing an issue, you should use the word `fix` before the issue number, like this: `"[fix #<issue_number>] <commit_type>: <commit_message>"`. Example: 40c58edf337f8b4b439dc26091b39b4def9bd519
- If you need to write different information in the commit, you can use the `git commit --amend` to edit the commit message and write more specific topics to it. Example: 9bb770ac502ae7c548403ebefda3d84f53d52399

*Commit types*
- `feat`: (new feature for the user, not a new feature for build script)
- `fix`: (bug fix for the user, not a fix to a build script)
- `docs`: (changes to the documentation)
- `style`: (formatting, missing semi colons, etc; no production code change)
- `refactor`: (refactoring production code, eg. renaming a variable)
- `test`: (adding missing tests, refactoring tests; no production code change)
- `chore`: (updating grunt tasks etc; no production code change)

If any doubts, you can comment here or you can email me (see in my profile) if is something beyond this issue scope. 😃

**Comment by Levysantiago** [comment]
And @SincerelyBrittany, if you think it's a relevant and interesting project, feel free to give a star 😄 ⭐
